package org.liufeng.course.bean;

/**
 *
 * app用户
 *
 */
public class AppUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.id
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.name
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String name;
    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.nickname
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.pwd
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.utype
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private Integer utype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.mobile
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.safetoken
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String safetoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.devicetoken
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String devicetoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.loginIp
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String loginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.avatar
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.pic_url
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.status
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.usertype
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private Integer usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.connectionstate
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String connectionstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.deviceUUID
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String deviceuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.deviceName
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String devicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.os
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.osVer
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String osver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.inviteCode
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String invitecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.openId
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.appVer
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private String appver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.createdtime
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private Integer createdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.updatetime
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private Integer updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.expiretime
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    private Integer expiretime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.id
     *
     * @return the value of app_user.id
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.id
     *
     * @param id the value for app_user.id
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.name
     *
     * @return the value of app_user.name
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.name
     *
     * @param name the value for app_user.name
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.nickname
     *
     * @return the value of app_user.nickname
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.nickname
     *
     * @param nickname the value for app_user.nickname
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.pwd
     *
     * @return the value of app_user.pwd
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.pwd
     *
     * @param pwd the value for app_user.pwd
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.utype
     *
     * @return the value of app_user.utype
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public Integer getUtype() {
        return utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.utype
     *
     * @param utype the value for app_user.utype
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setUtype(Integer utype) {
        this.utype = utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.mobile
     *
     * @return the value of app_user.mobile
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.mobile
     *
     * @param mobile the value for app_user.mobile
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.safetoken
     *
     * @return the value of app_user.safetoken
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getSafetoken() {
        return safetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.safetoken
     *
     * @param safetoken the value for app_user.safetoken
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setSafetoken(String safetoken) {
        this.safetoken = safetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.devicetoken
     *
     * @return the value of app_user.devicetoken
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getDevicetoken() {
        return devicetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.devicetoken
     *
     * @param devicetoken the value for app_user.devicetoken
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setDevicetoken(String devicetoken) {
        this.devicetoken = devicetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.loginIp
     *
     * @return the value of app_user.loginIp
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.loginIp
     *
     * @param loginip the value for app_user.loginIp
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.avatar
     *
     * @return the value of app_user.avatar
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.avatar
     *
     * @param avatar the value for app_user.avatar
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.pic_url
     *
     * @return the value of app_user.pic_url
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.pic_url
     *
     * @param picUrl the value for app_user.pic_url
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.status
     *
     * @return the value of app_user.status
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.status
     *
     * @param status the value for app_user.status
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.usertype
     *
     * @return the value of app_user.usertype
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.usertype
     *
     * @param usertype the value for app_user.usertype
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.connectionstate
     *
     * @return the value of app_user.connectionstate
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getConnectionstate() {
        return connectionstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.connectionstate
     *
     * @param connectionstate the value for app_user.connectionstate
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setConnectionstate(String connectionstate) {
        this.connectionstate = connectionstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.deviceUUID
     *
     * @return the value of app_user.deviceUUID
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getDeviceuuid() {
        return deviceuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.deviceUUID
     *
     * @param deviceuuid the value for app_user.deviceUUID
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setDeviceuuid(String deviceuuid) {
        this.deviceuuid = deviceuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.deviceName
     *
     * @return the value of app_user.deviceName
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getDevicename() {
        return devicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.deviceName
     *
     * @param devicename the value for app_user.deviceName
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setDevicename(String devicename) {
        this.devicename = devicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.os
     *
     * @return the value of app_user.os
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.os
     *
     * @param os the value for app_user.os
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setOs(String os) {
        this.os = os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.osVer
     *
     * @return the value of app_user.osVer
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getOsver() {
        return osver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.osVer
     *
     * @param osver the value for app_user.osVer
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setOsver(String osver) {
        this.osver = osver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.inviteCode
     *
     * @return the value of app_user.inviteCode
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getInvitecode() {
        return invitecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.inviteCode
     *
     * @param invitecode the value for app_user.inviteCode
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setInvitecode(String invitecode) {
        this.invitecode = invitecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.openId
     *
     * @return the value of app_user.openId
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.openId
     *
     * @param openid the value for app_user.openId
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.appVer
     *
     * @return the value of app_user.appVer
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public String getAppver() {
        return appver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.appVer
     *
     * @param appver the value for app_user.appVer
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setAppver(String appver) {
        this.appver = appver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.createdtime
     *
     * @return the value of app_user.createdtime
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public Integer getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.createdtime
     *
     * @param createdtime the value for app_user.createdtime
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setCreatedtime(Integer createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.updatetime
     *
     * @return the value of app_user.updatetime
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.updatetime
     *
     * @param updatetime the value for app_user.updatetime
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.expiretime
     *
     * @return the value of app_user.expiretime
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public Integer getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.expiretime
     *
     * @param expiretime the value for app_user.expiretime
     *
     * @mbggenerated Wed May 11 09:18:14 GMT+08:00 2016
     */
    public void setExpiretime(Integer expiretime) {
        this.expiretime = expiretime;
    }
}